### PR TITLE
BREAKING: v1

### PR DESCRIPTION
**Pull request by ebebbington**
Myself (edward) and Eric are both working on this PR (with only one of us working on it at the same time). Eric has done all the code changes to the source code

## Reasoning

....

## TODO

- Tests

### CODE REVIEW

**Comment by ebebbington** [comment]
going to work on adding/adjusting the tests

**Comment by ebebbington** [comment]
**unit tests are completed**

just some updates so we dont forget:

1. `Server#to` method needs to be implemented, where it can send to a `Channel`, `Server` or `Client`
2. Not all of the logic has been added to handle events from clients

This is found by the integration yesys

**Comment by ebebbington** [comment]
I think we'll favour #124 over this, but i need time to check

**Comment by ebebbington** [comment]
a good example of how to use this:

```ts
import { Server } from "./src/server.ts";
import { WebSocketClient } from "./src/websocket_client.ts";
const server = new Server({
  hostname: "localhost",
  port: 1447,
  protocol: "http",
});

server.run();

server.on("test", (event: CustomEvent) => {
  console.log(event);
});

console.log(`Running at ${server.address}`);

// Example using the connect handler
server.on<{ id: number }>("connect", (e: CustomEvent) => {
  const { id } = e.detail;
  console.log("server had a client connected: " + id);
});

// Example using the disconnect handler
server.on<{
  id: number;
  code: number;
  reason: string | "";
}>("disconnect", (e: CustomEvent) => {
  const { id, code, reason } = e.detail;
  console.log("server had a client disconnect:");
  console.log(id, code, reason);
  console.log(`|${reason}|`, typeof reason);
});

// Example using generics + custom channel handler and getting the data from the event
type UserMessage = {
  username: string;
  sender: number;
  id: number; // client socket id
};
server.on("channel", (event: CustomEvent<UserMessage>) => {
  console.log("got channel msg");
  const { username, sender, id } = event.detail;
  console.log(username, sender);

  // Example sending to all clients, specifying which channel it is for
  server.to("chat-message", {
    message: "yep, the server got your msg :)",
  });

  // example sending to a specific client
  server.to("chat-message", {
    message: "this message is only for you *wink wink*",
  }, id);

  // example sending to all OTHER clients TODO :: broadcast?
  server.broadcast("chat-message", {
    message: "You got this message but client with id of " + id +
      " shouldnt have",
  }, id);
});

const client = await WebSocketClient.create("ws://localhost:1447");
client.on<{ message: string }>("chat-message", async (packet) => {
  const { message } = packet;
  console.log("client got message:");
  console.log(message);
  await client.close();
});
console.log("gonna send msg");
client.to("channel", {
  username: "darth vader",
  sender: 69,
});
```

**Comment by ebebbington** [comment]
only problem is the integration test failing

**Comment by crookse** [comment]
working on this now. adding some logic to send client-to-client messages. also trying to make the `getHandler()` function not so huge

**Review by crookse — APPROVED** [review]
test

**Pull request merged**
