### PR TITLE
chore: Refactor wss tests

### PR DESCRIPTION
**Pull request by ebebbington**
**Description**

* Refactors app_3001 test

### CODE REVIEW

**Comment by ebebbington** [comment]
**TODO**
All we need to do is create the ws server (can copy code from the test and then comment out the whole rhum code, then run with `deno run`), and check it works with tls. Then uncomment the tests, make the changes needed and everything should work

**Comment by ebebbington** [comment]
Ok so this PR is ready for review, but it doesn't actually fix anything. It improves the test code a lot, and i am sick of not being to able to fix it :P So really, this PR is just an improvement. to the test code so when we *do come back to it*, it's easier to work with

Again, this fixes nothing, and changes nothing in the source code or the ci

**Comment by ebebbington** [comment]
In reference to #88

**Review by Guergeiro — APPROVED** [review]
Testing 👍🏿

**Review by crookse — APPROVED** [review]

**Pull request merged**
