### PR TITLE
chore: Update dependencies and bump version numbers across repo

### PR DESCRIPTION
**Pull request by drashbot**
This pull request was auto-generated by GitHub Actions.

### CODE REVIEW

**Comment by ebebbington** [comment]
hm, seems to be race conditions here or leaking ops... when this PR was made, the macos tests failed, i re ran and now the ubuntu tests failed

Gonna look into it

**Comment by ebebbington** [comment]
i can't figure it out D:

**Comment by saragee3** [comment]
I just ran the tests locally and it worked 🤔 i'll try and debug this

**Comment by ebebbington** [comment]
@saragee3 seems to be the integration tests, what i've done so far is commented out every test case in `app_3000` except for `Cannot send messages to channels a user hasn't connected to` (as this is one of the two cases that fail), and just re-run it about 10 times, and 1-2 of those times it fails

**Comment by ebebbington** [comment]
Ok, it looks to me, like the server hasn't finished sending mssages before we close it

Add this above `await server.close()` inthe test case mentionedabove:
```
const p = new Promise((resolve) => {
            setTimeout(() => {
              resolve('')
            }, 1000)
          })
          await p
```
I've ran this a dozen times, and the test. never fails

**Comment by ebebbington** [comment]
Ok i have 'fixed' the issue, but it. is kind of a hack... I also added `deno lint` to the ci pipeline, will need reviewing by @saragee3 @Guergeiro or @crookse

**Comment by crookse** [comment]
> Ok i have 'fixed' the issue, but it. is kind of a hack... I also added `deno lint` to the ci pipeline, will need reviewing by @saragee3 @Guergeiro or @crookse
> 
> Do we go with this hack? Do we continue to investigate it?

ewwwwwwwwwwwwwwwwwwww 🤮

**Comment by Guergeiro** [comment]
I mean, it's ugly, but it works and it's for testing purposes only... I remember once I had to do a [nasty fix](https://github.com/ufoscout/docker-compose-wait/) at a job because my tests started running and the connection was not ready, therefore making tests fail.
Sometimes is like that. The only way of going around this is having some logic on the server that says that it's ready to accept connections. After that, the client can start connecting or the test can run.

**Comment by ebebbington** [comment]
fml the commit was removed, ill add the code back now :P

**Comment by ebebbington** [comment]
erics response for ref purposes:

image

**Pull request merged**
